!----------------------------------------------------------------------------
!
! Hawkmatix Statistics Module for Fortran
! Official project page: http://www.hawkmatix.com/statistics.html
!
! Copyright 2014 Andrew Charles Hawkins (andrew.hawkins@hawkmatix.com)
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Lesser General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Lesser General Public License for more details.
!
! You should have received a copy of the GNU Lesser General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.
!
!----------------------------------------------------------------------------

MODULE STAT

IMPLICIT NONE
CONTAINS

! Maximum value
! MAXVAL(ARRAY, [DIM], [MASK])

! Minimum value
! MINVAL(ARRAY, [DIM], [MASK])

! Maximum location
! MAXLOC(ARRAY, [DIM], [MASK])

! Minimum location
! MINLOC(ARRAY, [DIM], [MASK])

! Arithmetic mean
DOUBLE PRECISION FUNCTION ARITHMETIC_MEAN(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

ARITHMETIC_MEAN = SUM(DATASET) / LENGTH

RETURN

END FUNCTION ARITHMETIC_MEAN

! Geometric mean
DOUBLE PRECISION FUNCTION GEOMETRIC_MEAN(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

GEOMETRIC_MEAN = PRODUCT(DATASET) ** (1.0D0 / LENGTH)

END FUNCTION GEOMETRIC_MEAN


! Harmonic mean
DOUBLE PRECISION FUNCTION HARMONIC_MEAN(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

HARMONIC_MEAN = LENGTH / SUM(1.0D0 / DATASET)

RETURN

END FUNCTION HARMONIC_MEAN

! Quadratic mean
DOUBLE PRECISION FUNCTION QUADRATIC_MEAN(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

QUADRATIC_MEAN = DSQRT(SUM(DATASET * DATASET) / LENGTH)

RETURN

END FUNCTION QUADRATIC_MEAN

! Generalized mean
DOUBLE PRECISION FUNCTION GENERALIZED_MEAN(DATASET, LENGTH, POWER)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH, POWER
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

GENERALIZED_MEAN = (SUM(DATASET ** POWER) / LENGTH) ** (1.0D0 / POWER)

RETURN

END FUNCTION GENERALIZED_MEAN

! Weighted mean
DOUBLE PRECISION FUNCTION WEIGHTED_MEAN(DATASET, WEIGHT, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET, WEIGHT

WEIGHTED_MEAN = SUM(DATASET * WEIGHT) / SUM(WEIGHT)

RETURN

END FUNCTION WEIGHTED_MEAN

! Median
DOUBLE PRECISION FUNCTION MEDIAN(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

MEDIAN = 0

RETURN

END FUNCTION MEDIAN

! Mode
DOUBLE PRECISION FUNCTION MODE(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

MODE = 0

RETURN

END FUNCTION MODE

! Range
DOUBLE PRECISION FUNCTION SRANGE(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

SRANGE = MAXVAL(DATASET) - MINVAL(DATASET)

RETURN

END FUNCTION SRANGE

! Midrange
DOUBLE PRECISION FUNCTION MIDRANGE(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

MIDRANGE = (MAXVAL(DATASET) + MINVAL(DATASET)) / 2.0D0

RETURN

END FUNCTION MIDRANGE

! Interquartile range
DOUBLE PRECISION FUNCTION IQRANGE(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

IQRANGE = 0

RETURN

END FUNCTION IQRANGE

! Trimean
DOUBLE PRECISION FUNCTION TRIMEAN(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

TRIMEAN = 0

RETURN

END FUNCTION TRIMEAN

! Variance
DOUBLE PRECISION FUNCTION VARIANCE(DATASET, LENGTH, CORRECTED)

IMPLICIT NONE

LOGICAL, INTENT(IN) :: CORRECTED
INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET
INTEGER :: i
DOUBLE PRECISION :: bulk, mean

bulk = 0.0D0
mean = ARITHMETIC_MEAN(DATASET, LENGTH)

DO i = 1, LENGTH
	bulk = bulk + (DATASET(i) - mean) ** 2
END DO

IF (CORRECTED .EQV. .TRUE.) THEN
	VARIANCE = bulk / (LENGTH - 1)
ELSE
	VARIANCE = bulk / LENGTH
END IF

RETURN

END FUNCTION VARIANCE

! Standard deviation
DOUBLE PRECISION FUNCTION STANDARD_DEVIATION(DATASET, LENGTH, CORRECTED)

IMPLICIT NONE

LOGICAL, INTENT(IN) :: CORRECTED
INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

STANDARD_DEVIATION = DSQRT(VARIANCE(DATASET, LENGTH, CORRECTED))

RETURN

END FUNCTION STANDARD_DEVIATION

! Mean absolute deviation
DOUBLE PRECISION FUNCTION MEAN_ABSOLUTE_DEVIATION(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET
INTEGER :: i
DOUBLE PRECISION :: bulk, mean

bulk = 0.0D0
mean = ARITHMETIC_MEAN(DATASET, LENGTH)

DO i = 1, LENGTH
	bulk = bulk + DABS(DATASET(i) - mean)
END DO

MEAN_ABSOLUTE_DEVIATION = bulk / LENGTH

RETURN

END FUNCTION MEAN_ABSOLUTE_DEVIATION

! Mean difference
DOUBLE PRECISION FUNCTION MEAN_DIFFERENCE(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET
INTEGER :: i, j
DOUBLE PRECISION :: bulk

bulk = 0.0D0

DO i = 1, LENGTH
	DO j = 1, LENGTH
		bulk = bulk + DABS(DATASET(i) - DATASET(j))
	END DO
END DO

MEAN_DIFFERENCE = bulk / (LENGTH ** 2)

RETURN

END FUNCTION MEAN_DIFFERENCE

! Relative mean difference
DOUBLE PRECISION FUNCTION RELATIVE_MEAN_DIFFERENCE(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

RELATIVE_MEAN_DIFFERENCE = MEAN_DIFFERENCE(DATASET, LENGTH) / ARITHMETIC_MEAN(DATASET, LENGTH)

RETURN

END FUNCTION RELATIVE_MEAN_DIFFERENCE

! Median absolute deviation
DOUBLE PRECISION FUNCTION MEDIAN_ABSOLUTE_DEVIATION(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET

MEDIAN_ABSOLUTE_DEVIATION = 0

RETURN

END FUNCTION MEDIAN_ABSOLUTE_DEVIATION

! Skewness
DOUBLE PRECISION FUNCTION SKEWNESS(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET
INTEGER :: i
DOUBLE PRECISION :: bulk, mean

bulk = 0.0D0
mean = ARITHMETIC_MEAN(DATASET, LENGTH)

DO i = 1, LENGTH
	bulk = bulk + (DATASET(i) - mean) ** 3
END DO

SKEWNESS = (bulk / LENGTH) / VARIANCE(DATASET, LENGTH, .FALSE.) ** (3 / 2.0D0)

RETURN

END FUNCTION SKEWNESS

! Kurtosis
DOUBLE PRECISION FUNCTION KURTOSIS(DATASET, LENGTH)

IMPLICIT NONE

INTEGER, INTENT(IN) :: LENGTH
DOUBLE PRECISION, DIMENSION(LENGTH), INTENT(IN) :: DATASET
INTEGER :: i
DOUBLE PRECISION :: bulk, mean

bulk = 0.0D0
mean = ARITHMETIC_MEAN(DATASET, LENGTH)

DO i = 1, LENGTH
	bulk = bulk + (DATASET(i) - mean) ** 4
END DO

KURTOSIS = (bulk / LENGTH) / VARIANCE(DATASET, LENGTH, .FALSE.) ** 2

RETURN

END FUNCTION KURTOSIS

! Factorial
DOUBLE PRECISION FUNCTION FACTORIAL(N)

IMPLICIT NONE

INTEGER, INTENT(IN) :: N

FACTORIAL = GAMMA(N + 1.0D0)

RETURN

END FUNCTION FACTORIAL

! Permutation
DOUBLE PRECISION FUNCTION PERMUTATION(N, K)

IMPLICIT NONE

INTEGER, INTENT(IN) :: N, K

PERMUTATION = FACTORIAL(N) / FACTORIAL(N - K)

END FUNCTION PERMUTATION

! Combination
DOUBLE PRECISION FUNCTION COMBINATION(N, K)

IMPLICIT NONE

INTEGER, INTENT(IN) :: N, K

COMBINATION = FACTORIAL(N) / (FACTORIAL(K) * FACTORIAL(N - K))

END FUNCTION COMBINATION

END MODULE STAT
